[package]
name = "zmp-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea = { git = "https://github.com/azalea-rs/azalea.git" }
serenity = { version = "0.12.0", default-features = false,  features = ["client", "gateway", "model", "rustls_backend", "utils", "framework"] }
poise = "0.6.1"
tokio = { version = "1.36.0", features = ["parking_lot", "macros", "rt-multi-thread", "rt"] }

parking_lot = "0.12.1"
anyhow = { version = "1.0.79", features = [] }
env_logger = "0.11.2"
tracing = "0.1.40"
regex = "1.10.2"
bevy_log = "0.13.0"