[package]
name = "zmp-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.6.1"
serenity = { version = "0.12.0", default-features = false,  features = ["client", "gateway", "model", "rustls_backend", "utils", "framework"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "rt"] }
env_logger = "0.10.0"
anyhow = "1.0.75"
tracing = "0.1.40"
regex = "1.10.2"
