[package]
name = "zmp-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.6"
serenity = { version = "0.11.6", default-features = false, features = ["client", "gateway", "model", "rustls_backend", "utils"]}
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "rt"] }
env_logger = "0.10.0"
shuttle-secrets = "0.30.1"
shuttle-poise = "0.30.1"
shuttle-runtime = "0.30.1"
anyhow = "1.0.75"
tracing = "0.1.40"
regex = "1.10.2"
cargo-shuttle = "0.30.1"
